name: Examples

on:
  workflow_dispatch:      # Manually start a workflow
  push:
    paths-ignore:
    - '.github/**'        # Ignore changes towards the .github directory
    - '**.md'             # Do no build if *.md files changes

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-14]
        example:
          - "examples/arduino-blink"
          - "examples/arduino-rmt-blink"
          - "examples/arduino-usb-keyboard"
          - "examples/arduino-wifiscan"
          - "examples/arduino-zigbee-light"
          - "examples/arduino-zigbee-switch"
          - "examples/espidf-arduino-h2zero-BLE_scan"
          #- "examples/espidf-arduino-matter-light"        # Windows compile fails -> Path length limit
          - "examples/espidf-arduino-blink"
          - "examples/espidf-arduino-littlefs"
          - "examples/espidf-blink"
          - "examples/espidf-coap-server"
          - "examples/espidf-exceptions"
          - "examples/espidf-hello-world"
          - "examples/espidf-http-request"
          - "examples/espidf-peripherals-uart"
          - "examples/espidf-peripherals-usb"
          - "examples/espidf-storage-sdcard"
          - "examples/espidf-ulp"
          - "examples/espidf-ulp-riscv"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio pkg install --global --platform symlink://.
      - name: Build examples
        run: |
          pio run -d ${{ matrix.example }}
