name: CI Examples Matter

on:
  workflow_dispatch:      # Manually start a workflow
  push:
    paths-ignore:
    - '.github/**'        # Ignore changes towards the .github directory
    - '**.md'             # Do no build if *.md files changes

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15]
        example:
          - "examples/espidf-arduino-matter-light"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          pip install wheel
          pip install -U https://github.com/pioarduino/platformio-core/archive/refs/tags/v6.1.18.zip
          pio pkg install --global --platform file://.
      - name: Build examples
        run: pio run -d ${{ matrix.example }}
