name: CI Examples

on:
  workflow_dispatch:      # Manually start a workflow
  push:
    paths-ignore:
    - '.github/**'        # Ignore changes towards the .github directory
    - '**.md'             # Do no build if *.md files changes

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15]
        example:
          - "examples/arduino-wifiscan"
          - "examples/espidf-ulp"
          - "examples/espidf-ulp-riscv"
          - "examples/espidf-ulp-lp"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          pip install wheel
          pip install -U https://github.com/pioarduino/platformio-core/archive/refs/tags/v6.1.18.zip
          pio pkg install --global --platform file://.
      - name: git clone Tasmota and add to examples
        if: "matrix.example == 'examples/tasmota'"
        run: |
          git clone -b development --depth 1 https://github.com/arendst/Tasmota.git examples/tasmota
          cp examples/tasmota_platformio_override.ini examples/tasmota/platformio_override.ini
      - name: Build examples
        if: "matrix.example != 'examples/espidf-arduino-matter-light' || matrix.os != 'windows-latest'"
        run: pio run -d ${{ matrix.example }}
